#
#Thu Mar 12 07:04:34 COT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, test-type, no-sandbox, ignore-certificate-errors, --window-size\=1200,900, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, disable-dev-shm-usage, disable-extensions, disable-web-security, disable-translate, disable-logging, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=true
browserName=chrome
